// <auto-generated />
namespace SGEDAO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class primeiraCarga : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(primeiraCarga));
        
        string IMigrationMetadata.Id
        {
            get { return "201809171855097_primeiraCarga"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
