// <auto-generated />
namespace SGEDAO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class terceiraCarga18092018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(terceiraCarga18092018));
        
        string IMigrationMetadata.Id
        {
            get { return "201809181934112_terceiraCarga18092018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
